### ISSUE TITLE
Add support for an `is` check

### ISSUE THREAD

**Issue by zoechi** [dart-lang/code_builder#101]
like
```dart
if(x is Foo) {
}
```
I wasn't able to find anything

**Comment by matanlurey** [comment]
Nope, contributions welcome!

**Comment by thosakwe** [comment]
Willing to take this on this weekend.

**Comment by thosakwe** [comment]
I'm a bit late, but I'll try to get this done.

I want to add this to the `ExpressionBuilder` interface:

```dart
/// `is` a reserved word; can't use
ExpressionBuilder isInstanceOf(TypeBuilder type);
```

Any better suggestions for the name, or is `isInstanceOf` ok?

**Comment by matanlurey** [comment]
Sounds good to me!

**Comment by thosakwe** [comment]
Cool!

**Comment by matanlurey** [comment]
Closed by https://github.com/dart-lang/code_builder/commit/4f322977129ae30df6fcf677b216045fd0b28e74.
