### ISSUE TITLE
Rename File to Library

### ISSUE THREAD

**Issue by natebosch** [dart-lang/code_builder#154]
the conflict makes outputting to a dart:io File a little annoying.

**Comment by matanlurey** [comment]
I'm trying to avoid a breaking change for just-sake-of something this small.

Is deprecating and adding an alias (i.e. `Library`) OK?

**Comment by natebosch** [comment]
Yeah I agree that a major version bump just for this isn't worthwhile. I think alias + deprecating makes sense for now and once we have other breaking changes we can drop it.
