### ISSUE TITLE
Escape quotes in stringLiteral expressions

### ISSUE THREAD

**Issue by natebosch** [dart-lang/code_builder#155]
A String with a `'` will not work. Since it's not clear whether double or single quotes are used we might want to escape quotes.

**Comment by matanlurey** [comment]
What would you prefer/see as ergonomic?

**Comment by natebosch** [comment]
I think `.replaceAll('\'', '\\\'').replaceAll('\"', '\\\"')` should be a relatively safe thing to do (unless folks are relying on it not being escaped today)

We could potentially just do `.replaceAll('\'', '\\\'')` if we know we'll only ever use single quotes for strings.
