### ISSUE TITLE
Accessing values in a map

### ISSUE THREAD

**Issue by xqwzts** [dart-lang/code_builder#159]
It looks like in v1 we used to be able to access values in a map by doing:

`reference('someMap')[literal(someKey)];`

But in v2 the following throws an exception:

`refer('someMap')[literal(someKey)];`
> NoSuchMethodError: Class 'Reference' has no instance method '[]'.
Receiver: Instance of 'Reference'
Tried calling: [](Instance of 'LiteralExpression')

**Comment by matanlurey** [comment]
Thanks! Should be addressed in https://github.com/dart-lang/code_builder/pull/161

**Comment by xqwzts** [comment]
Perfect, thanks!
