### ISSUE TITLE
Parameters cannot have a FunctionType type

### ISSUE THREAD

**Issue by natebosch** [dart-lang/code_builder#174]
It doesn't seem possible to write a Method which takes an argument which is a FunctionType because `FunctionType.type` [returns null](https://github.com/dart-lang/code_builder/blob/258fbc8b2aa65eb84a1283b085a4c82c66dc3800/lib/src/specs/type_function.dart#L61)

Failing test:
```dart
  test('should create a method with a funciton type argument', () {
    expect(
        new Method((b) => b
          ..name = 'foo'
          ..requiredParameters.add(new Parameter((b) => b
            ..type = new FunctionType((b) => b
              ..returnType = refer('String')
              ..requiredParameters.add(refer('int')))
            ..name = 'argument'))),
        equalsDart(r'''
          foo(String Function(int) argument)
          '''));
  });
```

**Comment by matanlurey** [comment]
Yup, that seems like a silly bug. Contributions welcome ;)

**Comment by natebosch** [comment]
I think it might require adding something like `FunctionTypeReference implements TypeReference` and `SpecVisitor.visitFunctionType`. I don't see a way to fit this in to the existing `FunctionType` implementation.

**Comment by natebosch** [comment]
There already is a `visitFunctionType` :) this shouldn't be too hard.
