### ISSUE TITLE
Intent to release: 3.0.0

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/code_builder#180]
Before we have lots more usage, we might want to try and ship 3.0.0.

Specifically, with the following breaking changes:
* Remove automatic `dartfmt` with use of `equalsDart`.
* Remove all uses of `Annotation`.
* Change `{Method|Constructor}.lambda` to default to `null` (infer).
* Remove all uses of `File`.

Any other ideas/thoughts? /cc @kevmoo @natebosch @alorenzen @thosakwe

**Comment by kevmoo** [comment]
Make sure you support latest dependencies?

**Comment by natebosch** [comment]
I've been trying to figure out whether we can add support for `if` and `else` and without digging too deeply I was worried they could only be done cleanly with breaking changes. It might be nice to experiment a bit more.

**Comment by matanlurey** [comment]
Sure. No rush.

I'd like to maybe get a `3.0.0-alpha` with BCs for google3 validation soon (TM), and we can decide on whether we want to include other changes before shipping 3.0-final. But no rush (and not this week).

**Comment by matanlurey** [comment]
Initial release as https://pub.dartlang.org/packages/code_builder/versions/3.0.0-alpha.

**Comment by natebosch** [comment]
Will migrating to `3.0.0` from angular fix and of the version solve madness? If so I'm in favor of doing that ASAP and not waiting for any more changes.

**Comment by matanlurey** [comment]
@natebosch It definitely will help, but I also don't mind depending on an alpha since Angular itself will be alpha until Dart 2.0 ships.

**Comment by natebosch** [comment]
Anything that can improve where we are would be appreciated. I've been trying to upgrade angular to the latest build_runner and running in to lots of pain (`pub upgrade` works but `pub get` fails 😢 )

**Comment by matanlurey** [comment]
3.0.0-alpha has landed in google3.

@natebosch @alorenzen @kevmoo any final feedback before 3.0.0-final?

**Comment by kevmoo** [comment]
I haven't played much with it. All for getting bits out there, though...

**Comment by kevmoo** [comment]
One blocker: https://github.com/dart-lang/code_builder/issues/184

**Comment by matanlurey** [comment]
Done.
