### ISSUE TITLE
Allow customizing the prefix for _PrefixedAllocator

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/code_builder#190]
Idea:

```dart
factory Allocator.simplePrefixing([String prefix = '_i') = _PrefixedAllocator;
```

**Comment by natebosch** [comment]
Who do we expect might use this?

**Comment by matanlurey** [comment]
I ended up not needing it myself, the idea was to have multiple emitters - but it is actually easier (and better) to have multiple emitters but a single allocator to de-dupe.
