### ISSUE TITLE
Bump built_value dependency to v5.0.0

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/code_builder#191]
v5.0.0 adds three restrictions: no using "extends", no importing "package:built_value/built_value.dart" with "show" or "as", and no using SDK collections in fields.

Unfortunately it looks like you have "extends Expression" on a built_value type. It would be trivial to fix by changing to "extends Object with Expression", but unfortunately this does not allow Expression to have a const constructor ... it actually looks like right now const classes are completely incompatible with mixins.

So it may be the only thing we can do is to remove `const` everywhere. Any ideas please?...

**Comment by davidmorgan** [comment]
One option is that I change the built_value restriction ... so that you _are_ allowed to extend a class provided it's got a single, no-arg const constructor.

Essentially working around the fact that the language doesn't recognize that this is a degenerate case that should be allowed :/

**Comment by matanlurey** [comment]
If you allow the single, no-arg const constructor it will obviously be easiest.

**Comment by davidmorgan** [comment]
On closer inspection I think code_builder's usage is fine, I'm going to relax the built_value_generator restrictions for specifically this use case.

I'll send a PR bumping the version of built_value once that's done.

**Comment by matanlurey** [comment]
Closed by #192
