### ISSUE TITLE
ExpressionBuilder should be assignable to StatementBuilder

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/code_builder#2]
An expression is also a statement. For example:

```dart
void main() {
  "blah".substring(1);  // expression used as statement
}
```

So this should be allowed:

```dart
var methodBuilder = new MethodBuilder(...);
methodBuilder.addStatement(new ExpressionBuilder.invoke('substring'd));
```

**Comment by matanlurey** [comment]
Sorry, let me clarify, you'd like to do:

```dart
var method = new MethodBuilder.returnVoid('main');
var statement = new StatementBuilder()
  ..addExpression(const LiteralString('blah').invoke('substring', positional: [
    const LiteralInt(1)
  ]));
method.addStatement(statement);
```

Is that right? Or do you _specifically_ mean that maybe we should allow:

```dart
// Option 1
new StatementBuilder.fromExpression(...)

// Option 2
expression.toStatement()
```

**Comment by yjbanov** [comment]
The end result would be like in the first example, but the way I was thinking about is that there wouldn't be any special API to add an expression. Instead, an expression is a special case of a statement. IOW, `ExpressionBuilder extends StatementBuilder` so you can pass an `ExpressionBuilder` to `addExpression` or anything else that takes a `StatementBuilder`.

In Dart you can use any expression as a statement, e.g.:

```dart
// A valid Dart program
void main() {
  5;
  null;
  'hello';
  []..add(4);
}
```

**Comment by yjbanov** [comment]
Or, maybe we should do what [the analyzer is doing](https://www.dartdocs.org/documentation/analyzer/0.29.0-alpha.0/analyzer/ExpressionStatement-class.html) :)

**Comment by yjbanov** [comment]
In that case, option 2 looks great.
