### ISSUE TITLE
Should `.asA` automatically wrap the expression in parens?

### ISSUE THREAD

**Issue by natebosch** [dart-lang/code_builder#213]
```dart
someExpression.asAs(refer('Iterable')).property('toList').call([]);
```

This code won't work because you end up with

```dart
someExpression as Iterable.toList()
```

It should be safe to always wrap `(someExpression as Iterable)`. In some cases it may be unnecessary, but I don't think it will hurt anything.

**Comment by matanlurey** [comment]
Yup, go ahead and always wrap with parens.

Given that the goal of code_builder is generating correct code, not necessarily readable, makes sense.
