### ISSUE TITLE
Migrate away from built_value

### ISSUE THREAD

**Issue by natebosch** [dart-lang/code_builder#219]
I'm not sure if it would be breaking...

I think we should hand code the builders. It's a little annoying but this package is used in a lot of infrastructure around codegen and the dep is pretty limiting.

@matanlurey - if you don't have a problem with this I can try to take a stab at a PR sometime in the next couple weeks.

**Comment by matanlurey** [comment]
I am totally fine with that. I don't _think_ it is a breaking change, but we could bump just in case.

**Comment by zoechi** [comment]
Currently it limits to be used with built_value: 0.6.0 because it depends on ^5.1.0

**Comment by matanlurey** [comment]
@natebosch Do you still want to do this?

**Comment by natebosch** [comment]
I think unfortunately this would be breaking. I took a look today and even if we want to allow the breaking change it'll take a lot of work.

I think we should leave this issue open and consider it for later. For now I'll probably just update the version we're using.

**Comment by davidmorgan** [comment]
This would definitely be nice--the current circular dependency between built_value and code_builder is an annoyance.

One relatively easy way to remove the dependency would be to remove the generator and just check in the .g.dart files; you could even move their content into the .dart files. To also remove the dependency on built_value you'd could either fork the `Built` and `Builder` interfaces into your own private version or just add the methods explicitly to the classes.

Technically this would be a breaking change for users, if they're relying on you implementing `Built`, but I don't see why anyone would do that.

**Comment by matanlurey** [comment]
Do we still want to do this? @natebosch @davidmorgan

**Comment by davidmorgan** [comment]
I'm not expecting any pain from this until `built_value` hits a new major version; that's rare enough that's I'm not too worried.

**Comment by natebosch** [comment]
This hasn't come up for me since so I don't know if there is enough motivation to tackle it.

**Comment by davidmorgan** [comment]
There haven't been any breaking changes to `built_value`--we can revisit this if there are, I guess. Thanks.
