### ISSUE TITLE
omit optional new in constructor calls

### ISSUE THREAD

**Issue by natebosch** [dart-lang/code_builder#220]

**Comment by matanlurey** [comment]
@natebosch Is it worth this being behind a flag? Is this a breaking change if not?

**Comment by natebosch** [comment]
I don't think we need this to be behind a flag as long as the minimum SDK constraint is one that has Dart 2 mode by default.

**Comment by matanlurey** [comment]
Sg. Open to PRs here, or I can do it myself later this week.

**Comment by eredo** [comment]
Any work done on this? Otherwise I can pick it up this week. Just came across this while working on dartson. Same applies for #221
