### ISSUE TITLE
omit optional const in const constructor calls

### ISSUE THREAD

**Issue by natebosch** [dart-lang/code_builder#221]
This will be trickier than omitting `new`, because only those which are already in const contexts can be omitted.

**Comment by matanlurey** [comment]
Might need to augment the emitter so it knows where we are currently in a `const` context.

**Comment by matanlurey** [comment]
@natebosch Is it worth this being behind a flag? Is this a breaking change if not?

**Comment by kevmoo** [comment]
@natebosch – see https://github.com/dart-lang/code_builder/pull/238
