### ISSUE TITLE
StatementBuilder is missing generics

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/code_builder#23]
the following doesn't work:
new LibraryBuilder().addMember(literal(false).asConst('foo'));

ERROR: The argument type 'StatementBuilder' can't be assigned to the parameter type 'AstBuilder<CompilationUnitMember>'.

**Comment by matanlurey** [comment]
Apparently this is more of an issue of not being able to type `StatementBuilder`.

I'm going to loosen the addMember(...) call until I have a better fix.
