### ISSUE TITLE
Add "fromElement" constructor to specs

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/code_builder#234]
A common use-case when creating a code-generator (using source_gen) is to convert analyzer `Element` into code_builder `Spec`.

But at the moment, there's no easy way to do such a conversion, so we have to do it ourselves. This would make sense for code_builder to take care of this. Example:

```dart
FunctionElement element;
var type = FunctionType.fromFunctionElement(element);
```

**Comment by matanlurey** [comment]
We do not want a dependency on analyzer, as it makes it difficult to rev this project.
