### ISSUE TITLE
Support for `OR` operator

### ISSUE THREAD

**Issue by dmdashenkov** [dart-lang/code_builder#247]
There is `Expression.and(other)` method which produces an expression which performs logical `AND` operation. However, there is no `Expression.or(other)` method.

I use `code_builder` of version 3.2.0.

**Comment by natebosch** [comment]
Should be straightforward to add by following the pattern (and tests) for `Expression.and`. Want to open a PR @dmdashenkov ?

**Comment by ddashenkov** [comment]
@natebosch, seems like I cannot create a branch in this repository. Should I fork and create a pull request?

P.S. This is my second GitHub account.

**Comment by natebosch** [comment]
> Should I fork and create a pull request?

Yup 😄
