### ISSUE TITLE
How to call super method in construtor

### ISSUE THREAD

**Issue by huhuang03** [dart-lang/code_builder#258]
I want generate constructor like this(call super in constructor):
```
Class Foo extends Bar {
  Foo(): super(value1);
}
```

But I done't know how to call the super method in code like this:
```
var c = Class((b) => b
    ..constructors.add(this._buildConstructor())
    );

Constructor _buildConstructor() {
    return Constructor((c) {c
      ..body = Code('some code');
    });
}
```

I have search the [ConstructorBuilder class api](https://pub.dev/documentation/code_builder/latest/code_builder/ConstructorBuilder-class.html), but no found.

**Comment by natebosch** [comment]
I think it would be something like:

```dart
..constructors.add(Constructor((b) => b
    ..initializers.add(refer('super').call(arguments).code))
```

**Comment by huhuang03** [comment]
Thanks.
Test and works.

**Comment by kateile** [comment]
@natebosch hi, how can I archive something like
```dart
abstract class MdPage extends StatelessWidget {
  const MdPage({
    Key? key,
  }) : super(key: key);
}
```

**Comment by natebosch** [comment]
@kateile - It would be something like

```dart
  final c = Class((b) => b
    ..name = 'MdPage'
    ..extend = refer('StatelessWidget')
    ..constructors.add(Constructor((b) => b
      ..optionalParameters.add(Parameter((b) => b
        ..named = true
        ..name = 'key'
        ..type = refer('Key?')))
      ..initializers
          .add(refer('super').call([], {'key': refer('key')}).code))));
```

There is a limitation though - here I put `refer('Key?')` which means the `?` will be emitted ignoring the `useNullSafetySyntax` argument on the `DartEmitter`. I don't think we have an existing feature request for explicit support of nullability on `refer` for types, so you may want to file one.

**Comment by kateile** [comment]
@natebosch thanks
