### ISSUE TITLE
The method's optionalParameters seems to always parse into positional parameters[]?

### ISSUE THREAD

**Issue by nikeorever** [dart-lang/code_builder#259]
But optional parameters can be either **named** or **positional** in Dart

**Comment by natebosch** [comment]
The `Parameter` class can be set to be `named`.
https://pub.dev/documentation/code_builder/latest/code_builder/ParameterBuilder/named.html

```dart
      ..optionalParameters.add(Parameter((b) => b
        ..name = 'someArgument'
        ..named = true
        ..type = refer('String')))
```

**Comment by nikeorever** [comment]
Thanks
