### ISSUE TITLE
type_reference.g.dart file is broken after running build_runner

### ISSUE THREAD

**Issue by the4thfloor** [dart-lang/code_builder#261]
When I call `pub run build_runner build` to re-generate all `.g.dart` files, the `type_reference.g.dart` is broken. It looks that `built_value`(?) removes some references in the generated file. If you remove the `implements Reference` in the `type_reference.dart` file the code generation works, but this breaks other things :-(

error: Missing concrete implementations of 'getter TypeReference.symbol' and 'getter TypeReference.url'.  (non_abstract_class_inherits_abstract_member at [code_builder] lib/src/specs/type_reference.g.dart:9)

Dart VM version: 2.7.0
built_value: 7.0.4

**Comment by nishtahir** [comment]
I can confirm. I'm running into the same issue.

**Comment by matanlurey** [comment]
Closed as stale (people have contributed since).
