### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by the4thfloor** [dart-lang/code_builder#262]
I want to add support for `mixin`s but it is really hard to do that.

To get started I cloned the project, renamed `build.disabled.yaml` to `build.yaml`,  called `pub get` and `pub run build_runner build`. It `Found 10 declared outputs which already exist on disk.` and asked me what to do, and I selected `1 - Delete`. 

After the files are re-generated, the project is broken, see https://github.com/dart-lang/code_builder/issues/261

So I did reset all changes via `git reset` to get a working version.

Now I have a working copy of the project and I began to add a `specs/mixin.dart` file (I copied the content of the `specs/class.dart` file but renamed everything to `Mixin`).

My first modification was to remove `BuiltList<Reference> get mixins;` and `ListBuilder<Reference> mixins = ListBuilder<Reference>();` (you remember I copied the content of the `specs/class.dart` file), because a `mixin` cant have other `mixin`s.

I called `pub run build_runner build` again to regenerate the `specs/mixin.g.dart` file and bum:

```
$ pub run build_runner build
Unable to spawn isolate: lib/src/specs/mixin.g.dart:83:25: Error: The getter 'mixins' isn't defined for the class 'Mixin'.
 - 'Mixin' is from 'package:code_builder/src/specs/mixin.dart' ('lib/src/specs/mixin.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'mixins'.
        mixins == other.mixins &&
                        ^^^^^^
lib/src/specs/mixin.g.dart:167:18: Error: Superclass has no getter named 'mixins'.
    return super.mixins ??= new ListBuilder<Reference>();
                 ^^^^^^
lib/src/specs/mixin.g.dart:167:18: Error: Superclass has no setter named 'mixins'.
    return super.mixins ??= new ListBuilder<Reference>();
                 ^^^^^^
lib/src/specs/mixin.g.dart:173:11: Error: Superclass has no setter named 'mixins'.
    super.mixins = mixins;
          ^^^^^^
lib/src/specs/mixin.g.dart:243:13: Error: Superclass has no setter named 'mixins'.
      super.mixins = _$v.mixins?.toBuilder();
            ^^^^^^
```

When I remove all `mixin` stuff in the `specs/mixin.g.dart` it works, but it can't be the solution. I mean I use code generation to generate code and not to write it by hand.

I'm not a code generation expert, I use it some times for Flutter projects, but there I never run in this problem.

So my final question is: What is the right way to re-generate code when the defining class has changed?

**Comment by TarekkMA** [comment]
The instructions which are posted in the README.md file offer a solution for this issue.

```
$ pub global activate build_runner
$ mv build.disabled.yaml build.yaml
$ pub global run build_runner build --delete-conflicting-outputs
$ mv build.yaml build.disabled.yaml
```
