### ISSUE TITLE
update Getting Started

### ISSUE THREAD

**Issue by the4thfloor** [dart-lang/code_builder#265]
Please review my changes to the Getting Started documentation and merge them.

You can find my changes here: https://github.com/the4thfloor/code_builder_wiki/commit/17bda52da1d0e0354fb1d701de6d367dd27226bf

Github doesn't support PR for the wiki page, you need to merge them manually.

**Comment by natebosch** [comment]
The link doesn't exist anymore.

I _think_ our wiki might be community editable - you can feel free to make changes there and if you'd like them reviewed you can file an issue pointing at the commit after the fact. Thanks!
