### ISSUE TITLE
Cannot create a TypeReference to a nullable type

### ISSUE THREAD

**Issue by srawlins** [dart-lang/code_builder#270]
If I try to build a TypeReference putting a `?` at the end of `symbol`, it puts it before type arguments.

```dart
TypeReference((TypeReferenceBuilder b) {
    b
      ..symbol = '${type.name}?'
      ..url = _typeImport(type)
      ..types.addAll(type.typeArguments.map(_typeReference));
  });
```

given `type` is the DartType for `List<Foo>`, then this results in `List?<Foo>`.

I don't see a way to create, e.g. `List<Foo>?`.

**Comment by natebosch** [comment]
We probably have a fair amount of work ahead of us to support nullable types. It likely needs to be a new field on `TypeRefeference`

**Comment by natebosch** [comment]
We also, I think, will need to add support for `!` operator.

**Comment by srawlins** [comment]
Before I mail out a PR, I'd like feedback on the broad design; it's quite simple:

TypeReference needs a new field to indicate whether the emitter should emit a `?` at the end of the type. The wrinkle though, is that technically a `?` should _not_ be emitted for a nullable type if the library being emitted is not using the Null Safety type system. Here are a few ideas:

1. Add a `bool isNullable` field, nullable - a `?` would be emitted if this field is `true`. I'm not crazy about this because of the above technicality.
2. Add a `bool isExplicitlyNullable` field - a `?` would be emitted if this field is `true`. The name here makes the intention more clear, but it sure is a mouthful. 😦 
3. Add a `String nullabilitySuffix` field - users would explicitly pass `"?"` to emit a `?`. This is almost certainly a bad API, but is even closer to expressing what I want: the TypeReference builder asks the code building it "do you want me to add a `?` or not?"
4. Add an enum, `enum NullabilitySuffix { none, question }`, and a `NullabilitySuffix nullabilitySuffix` field, nullable or defaults to `NullabilitySuffix.none` - Obviously a `?` would be emitted if this field is `NullabilitySuffix.question`. Rather verbose though...

WDYT? Better name suggestions?

Am I right in thinking that the users of code_builder always know, when building a TypeReference, that they're building for a Null Safety library or not? Should the emitter control whether or not to print a `?` for a nullable type? I couldn't see how it would have that information...

**Comment by matanlurey** [comment]
We had a few points at time where it was required to tell the emitter if you wanted a particular language feature or not (I think opt-in for new function syntax, or something), so I could imagine a `enableNullability: true|false` as part of the emitter that ignores `.isNullable` if `false`?

**Comment by natebosch** [comment]
> Am I right in thinking that the users of code_builder always know, when building a TypeReference, that they're building for a Null Safety library or not?

Yes they will almost certainly have to. We can give utilities to help, but we're likely going to avoid any build system magic to do it for them.

> I could imagine a `enableNullability: true|false` as part of the emitter that ignores `.isNullable` if `false`?

That could work, we could at least play around with `enableNullability` turning on or off both `?` and `!` in the emitted code. I worry that most codegen authors will still need to think about much more than this - and might end up with entirely separate code paths for null safe output, but I don't know that it should prevent us from supporting suppressing them in the emitter if that does work for some folks.
