### ISSUE TITLE
How to build 'part (of)' expression?

### ISSUE THREAD

**Issue by chenenyu** [dart-lang/code_builder#271]
Code like `part (of) 'xxx.dart';`, what should i do?

**Comment by smkhalsa** [comment]
@chenenyu did you figure this out?

**Comment by chenenyu** [comment]
@smkhalsa No...

**Comment by smkhalsa** [comment]
this was closed in #269

**Comment by chenenyu** [comment]
@smkhalsa `part of` directive is also required...
