### ISSUE TITLE
factory const

### ISSUE THREAD

**Issue by vr19860507** [dart-lang/code_builder#288]
Inside the DartEmitter class, in the visitConstructor method you should swap these two blocks!
```
if (spec.factory) {
      output.write('factory ');
}

if (spec.constant) {
      output.write('const ');
}
```
The first must be "const"!

**Comment by natebosch** [comment]
I'm not sure if we support redirecting factories today, which is the only place this would come up...

**Comment by natebosch** [comment]
Looks like we do - there is a `redirect` field.

PRs are welcome 😄
