### ISSUE TITLE
Order import directives

### ISSUE THREAD

**Issue by srawlins** [dart-lang/code_builder#307]
Just to comply with the `directives_ordering` lint. I get that this is not high priority 👍 

It would be nice if at least `dart:` imports were above the rest. Maybe it would be a big refactor to both sort directives, _and_ have the prefixes remain sorted.

**Comment by matanlurey** [comment]
If there is a reasonable way to do this, sounds good to me!

**Comment by srawlins** [comment]
My bad, DartEmitter has `orderDirectives: true`. Boom.
