### ISSUE TITLE
Add an API to convert a Method to a function literal with its type parameters

### ISSUE THREAD

**Issue by srawlins** [dart-lang/code_builder#309]
If I define a Method like:

```dart
Method((b) {
    var typeT = TypeReference((b) => b..symbol = 'T');
    b.types.add(typeT);
    b.requiredParameters.add(Parameter((b) => b..name = 'arg'..type = typeT));
    b.body = Code('');
});
```

then `Method.closure` returns `(T arg) {}`. This is invalid Dart code as there is no `T` type in scope. I want it to return the generic function literal: `<T>(T arg) {}`.

I'm sure there is a reason for clearing the types in `toClosure`, so I suspect a new API is needed. :( `Method.closure` is a getter, not a function, so we can't add an optional parameter there... Something like `toGenericClosure`? Happy to contribute.

**Comment by matanlurey** [comment]
`toGenericClosure` seems fine to me

**Comment by srawlins** [comment]
Thanks, I'll mail a PR!
