### ISSUE TITLE
Is there support for generating classes with fields of types not in the dart:core library?

### ISSUE THREAD

**Issue by anthonyorona** [dart-lang/code_builder#329]
I'd appreciate an insight into this. I am trying to generate code from .YAML files and have grepped together the following:

    @override
    Future<void> build(BuildStep buildStep) async {
      File file = new File(path);
      final classYaml = await () async {
        if ((await file.exists()) == true) {
          String content = await file.readAsString();
          return await loadYaml(content) as Map;
        } else {
          throw new FormatException();
        }
      }();
  
      List<Field> fields = classYaml['fields'].map<Field>((field) {
        return Field((b) => b
          ..name = field['name']
          ..type = refer('MyCustomDataField'));
      }).toList();
  
      final message = Class(
        (b) => b
          ..name = className
          ..extend = refer('MyCustomBaseClass')
          ..fields.add(Field((b) => b
            ..name = 'name'
            ..type = refer('String')))
          ..fields.addAll(fields),
      );
  
      final result = <Spec>[message];
      final library = Library((b) => b.body.addAll(result));
      final emitter = DartEmitter(Allocator.simplePrefixing());
      await buildStep.writeAsString(
          buildStep.inputId.changeExtension('.dart'), DartFormatter().format('${library.accept(emitter)}'));
    }

This works to add MyCustomBaseClass and MyCustomDataField, but the generated code is missing the imports. How can I ensure that the imports that I want are in the generated source files?

**Comment by srawlins** [comment]
See the optional `url` parameter on [`refer`](https://pub.dev/documentation/code_builder/latest/code_builder/refer.html). This will ensure the correct imports are included.
