### ISSUE TITLE
How can I call a named constructor with arguments when defining Class fields?

### ISSUE THREAD

**Issue by anthonyorona** [dart-lang/code_builder#330]
I want to generate dart classes from a YAML schema. I define my fields as follows:

      List<Field> fields = messageYaml['fields'].map<Field>((field) {
        return Field((b) => b
          ..assignment = Reference('CustomVar', 'package:sandbox/types/custom_var.dart').newInstance([]).code
          ..name = field['name']
          ..modifier = FieldModifier.final$
          ..type = refer('CustomVar', 'package:sandbox/types/custom_var.dart'));
      }).toList();

This works fine calling the default constructor. What I cannot figure out is how I call my named constructor or how to even pass my YAML to this constructor..

     CustomVar.fromYaml(YamlMap yaml);
     or...
    CustomVar(YamlMap yaml);

I know this is probably not the best location to ask these questions, but this is not something a lot of people have knowledge about so the issue tracker seemed like the best place to ask :)

**Comment by anthonyorona** [comment]
I've changed my approach to this:

    Map<String, MyCustomVariable> fieldMap = messageYaml['fields'].map<String, MyCustomVariable>(
        (_, field) => MapEntry(field['name'], MyCustomVariable())
    );

    Field fields = Field((b) => b
        ..assignment = Reference(
            'Map<String, MyCustomVariable>',
            'package:sandbox/variables/my_custom_variable.dart'
        ).newInstance([fieldMap]).code
        ..name = 'fields'
        ..modifier = FieldModifier.final$
        ..type = refer('MyCustomVariable', 'package:sandbox/variables/my_custom_variable.dart'));

But same issue

**Comment by srawlins** [comment]
Something like `assignment = refer('Map').property('namedConstructor').call([arguments])` might work.

**Comment by anthonyorona** [comment]
Thank you! I did this...which seems kind of janky (not in the flutter sense)

            Reference('HLVariable', 'package:sandbox/formats/my_custom_variable.dart').property('initialize').call([
              literalString('${field['a']}'),
              literalString('${field['b']}'),
              literalString('${field['c']}'),
              literalString('${field['d']}'),
              literalString('${field['e']}'),
              literalString('${field['f']}'),
        ]).code

I can't figure out how to pass in kwargs based off the docs for [Expression.call](https://pub.dev/documentation/code_builder/latest/code_builder/Expression/call.html)

**Comment by srawlins** [comment]
What do you mean by kwargs?

**Comment by anthonyorona** [comment]
keyword arguments, named arguments, or positional parameters

Expression call(
  Iterable<Expression> positionalArguments, [
  **_Map<String, Expression> namedArguments = const {},_**
  List<Reference> typeArguments = const [],
])

**Comment by srawlins** [comment]
Dart does not have keyword arguments. You can see there in the signature how positional and named arguments are passed.

**Comment by anthonyorona** [comment]
Not to split hairs but [those are equivalent terms ](https://en.wikipedia.org/wiki/Named_parameter). Unless there is some reason to distinguish kwargs from named arguments. 

I looked at it more closely and this is what I arrived at. I'm going to post the snippet so someone in the future can see an example of usage:

    Field fields = Field((b) => b
      ..assignment = refer('').newInstance([
        literalMap({
          for (var f in messageYaml['fields'])
            literalString(f['name']):
                Reference('MyCustomVariable', 'package:sandbox/message/my_custom_variable.dart').property('initialize').call([], {
              'a': literalString(f['a']),
              'b': literalNum(f['b']),
              'c': literalString(f['c']),
              'd': literalNum(f['d']),
              'e': literalString(f['e']),
              'f': literalString(f['f'])
            }),
        })
      ]).code
      ..name = 'fields'
      ..type = refer('Map<String, MyCustomVariable>')
      ..modifier = FieldModifier.final$);

This library is very clever but I find it a bit difficult to jump into because it feels like a DSL with little tutorial. Going through the tests and example has gotten me to where I want to be, and I liked this [SO answer](https://stackoverflow.com/a/53272362/6615337) from @natebosch
