### ISSUE TITLE
`Expression.assign` is confusing: Either documentation or output is wrong

### ISSUE THREAD

**Issue by emme1444** [dart-lang/code_builder#343]
Given the following code

```dart
import "package:code_builder/code_builder.dart";

void main() {
  final emitter = DartEmitter();

  final e1 = refer("Hello").newInstance([]).assignFinal("hello");
  final e2 = refer("Hello").newInstance([]).assign(refer("hello"));

  print(e1.accept(emitter));
  print(e2.accept(emitter));
}
```

Personally, I would expect it to print:

```dart
final hello = Hello()
hello = Hello()
```

As I'm essentially `assign`ing an expression to a variable reference.

And, in fact, [the documentation for `Expression.assign`](https://pub.dev/documentation/code_builder/latest/code_builder/Expression/assign.html) states:

> Return `{other} = {this}`.

where `{other}` is `hello` and `{this}` is `Hello()`.

However, the above code produces the output like so:

```dart
final hello = Hello()
Hello() = hello
```

Is this a bug in the package or a documentation error?

Like I said, personally, it makes sense for it to output the former. If the actual output here (the latter) is the intended output, please update the documentation (I can of course create a PR). And also, would adding `Expression.assignTo`, which produces the former, be a possibility (creating a new issue of course)?

Thanks!

**Comment by natebosch** [comment]
I can fix the argument order in the doc.

I'm not sure I agree that `assign` should match `assignFinal` and `assignVar`. If anything, I think that `assignFinal` and `assignVar` should be dropped. `assign` feels like it matches the rest of the class more closely.

I have two proposals, but I'm not sure if this will be high enough priority to get immediate attention. Which proposal you like may depend more on whether `assign` or `assignVar` "feels" more in line with the rest of the API to you.

## Drop (deprecate) `assignFinal/Var` add `declareFinal/Var`

It in general feels more in line with how I think about writing code, and how much of this library feels to work with, to write `declareFinal('foo').assign(someExpression)` vs `someExpression.assignFinal('foo')`, and `refer('foo').assign(someExpression)` vs `someExpression.assignTo(refer('foo'))`.

## Add `assignTo`

We could either keep, or deprecate `assign`, depending on how useful folks think it is. We could add `assignTo` which matches `assignFinal` and `assignVar`.

Thoughts @jakemac53 @srawlins @matanlurey ?

**Comment by jakemac53** [comment]
+1 for `declareFinal` etc, that makes more sense to me
