### ISSUE TITLE
Generated code has no import statement

### ISSUE THREAD

**Issue by kateile** [dart-lang/code_builder#349]
Hi, I think am missing something on how generated code should have import statements. I am using `Reference` to pass `symbol` and `url` hoping that import will be on output but I get none.

Here is the sample of my code
```dart
import 'dart:io';
import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

/// A .
class Generator {
  /// R
  read() {
    String contents = File('./README.md').readAsStringSync();

    final animal = Class(
      (b) => b
        ..name = 'Animal'
        ..extend = const Reference('MdPage', 'package:md2dart/md2dart.dart') //HERE
        ..constructors.add(
          Constructor(
            (b) => b
              ..initializers.add(refer('super').call([]).code) //TROUBLE HERE TOO
              ..constant = true
              ..optionalParameters.add(
                Parameter(
                  (b) => b
                    ..name = 'key'
                    ..type = refer('Key?', 'package:flutter/material.dart') //HERE
                    ..named = true,
                ),
              ),
          ),
        )
        ..methods.addAll(
          [
            Method(
              (b) => b
                ..name = 'getContent'
                ..body = Code(
                  'return """\n$contents\n""";',
                )
                ..returns = refer('String')
                ..annotations.addAll([refer('override')]),
            ),
          ],
        ),
    );

    final emitter = DartEmitter(
      orderDirectives: true,
    );

    final kode = DartFormatter().format('${animal.accept(emitter)}');

    File('./lib/output.dart').writeAsStringSync(kode);
  }
}
```

output

```dart
class Animal extends MdPage {
  const Animal({Key? key}) : super();

  @override
  String getContent() {
    return """
This is README. 
""";
  }
}
```

But what I want is output to have these 2 imports at the beginning 
```dart
import 'package:flutter/material.dart';
import 'package:md2dart/md_page.dart';
```
as well as `super();` to be `super(key : key);` as in flutter widgets which I also can't figure out how..

Any help will be much appreciated.

**Comment by Snehal-Singh174** [comment]
import 'dart:io';
import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

/// A .
class Generator {
  /// R
  read() {
      String contents = File('./README.md').readAsStringSync();

      final animal = Library((lib) {
        lib.directives.addAll([
          Directive.import('package:flutter/material.dart'),
          Directive.import('package:md2dart/md_page.dart')
        ]);
        lib.body.add(Class(
              (b) => b
            ..name = 'Animal'
            ..extend =
            const Reference('MdPage', 'package:md2dart/md2dart.dart') //HERE
            ..constructors.add(
              Constructor(
                    (b) => b
                  ..initializers
                      .add(refer('super').call([refer('key : key')]).code) //TROUBLE HERE TOO
                  ..constant = true
                  ..optionalParameters.add(
                    Parameter(
                          (b) => b
                        ..name = 'key'
                        ..type =
                        refer('Key?', 'package:flutter/material.dart') //HERE
                        ..named = true,
                    ),
                  ),
              ),
            )
            ..methods.addAll(
              [
                Method(
                      (b) => b
                    ..name = 'getContent'
                    ..body = Code(
                      'return """\n$contents\n""";',
                    )
                    ..returns = refer('String')
                    ..annotations.addAll([refer('override')]),
                ),
              ],
            ),
        ));
      });

      final emitter = DartEmitter(
        orderDirectives: true,
      );

      final kode = DartFormatter().format('${animal.accept(emitter)}');

      File('./lib/output.dart').writeAsStringSync(kode);
    }
}

> Hi, I think am missing something on how generated code should have import statements. I am using `Reference` to pass `symbol` and `url` hoping that import will be on output but I get none.
> 
> Here is the sample of my code
> 
> ```dart
> import 'dart:io';
> import 'package:code_builder/code_builder.dart';
> import 'package:dart_style/dart_style.dart';
> 
> /// A .
> class Generator {
>   /// R
>   read() {
>     String contents = File('./README.md').readAsStringSync();
> 
>     final animal = Class(
>       (b) => b
>         ..name = 'Animal'
>         ..extend = const Reference('MdPage', 'package:md2dart/md2dart.dart') //HERE
>         ..constructors.add(
>           Constructor(
>             (b) => b
>               ..initializers.add(refer('super').call([]).code) //TROUBLE HERE TOO
>               ..constant = true
>               ..optionalParameters.add(
>                 Parameter(
>                   (b) => b
>                     ..name = 'key'
>                     ..type = refer('Key?', 'package:flutter/material.dart') //HERE
>                     ..named = true,
>                 ),
>               ),
>           ),
>         )
>         ..methods.addAll(
>           [
>             Method(
>               (b) => b
>                 ..name = 'getContent'
>                 ..body = Code(
>                   'return """\n$contents\n""";',
>                 )
>                 ..returns = refer('String')
>                 ..annotations.addAll([refer('override')]),
>             ),
>           ],
>         ),
>     );
> 
>     final emitter = DartEmitter(
>       orderDirectives: true,
>     );
> 
>     final kode = DartFormatter().format('${animal.accept(emitter)}');
> 
>     File('./lib/output.dart').writeAsStringSync(kode);
>   }
> }
> ```
> 
> output
> 
> ```dart
> class Animal extends MdPage {
>   const Animal({Key? key}) : super();
> 
>   @override
>   String getContent() {
>     return """
> This is README. 
> """;
>   }
> }
> ```
> 
> But what I want is output to have these 2 imports at the beginning
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:md2dart/md_page.dart';
> ```
> 
> as well as `super();` to be `super(key : key);` as in flutter widgets which I also can't figure out how..
> 
> Any help will be much appreciated.

**Comment by natebosch** [comment]
Emitting the `Class` will give you only the class definition, without the imports.
To emit an entire library, create a `Library` instance with your `Class` as one of the members.

```dart
    //...
    final emitter = DartEmitter(
      orderDirectives: true,
    );
    final library = Library((l) => l..body.add(animal));
    final kode = DartFormatter().format('${library.accept(emitter)}');
```

**Comment by Robbendebiene** [comment]
@natebosch This does only work when using `DartEmitter(allocator: Allocator())` or `DartEmitter.scoped()` but not for `DartEmitter()`, because it defaults to `Allocator.none`
