### ISSUE TITLE
Darttype.element as ClassElement, but element2 was prompted after the upgrade

### ISSUE THREAD

**Issue by xiaocode337317439** [dart-lang/code_builder#374]
Darttype. element as ClassElement
Not sure how to convert to ClassElement after using element2 ?

```dart
        final ele = type.element as ClassElement; // type => DartType
        // final ele = type as InterfaceType;
        final toJson = ele.lookUpMethod('toJson', ele.library);
        // final toJson = ele.getMethod("toJson");
        if (toJson == null) {
          value = refer("jsonEncode($displayName)");
        } else {
          value = refer("$displayName?.toJson()");
        }
```

**Comment by srawlins** [comment]
CC @scheglov

**Comment by scheglov** [comment]
`InterfaceType.element2` is `InterfaceElement`, and will be in future version not only `ClassElement`, but also `EnumElement`, or `MixinElement`. Right now both are also `ClassElement`, but we will separate them in the next breaking changes version. I think you might use `InterfaceElement` methods, without casting to `ClassElement`.

**Comment by xiaocode337317439** [comment]
> `InterfaceType.element2` is `InterfaceElement`, and will be in future version not only `ClassElement`, but also `EnumElement`, or `MixinElement`. Right now both are also `ClassElement`, but we will separate them in the next breaking changes version. I think you might use `InterfaceElement` methods, without casting to `ClassElement`.


How should DartType be converted to InterfaceType?

**Comment by xiaocode337317439** [comment]
> > `InterfaceType.element2` is `InterfaceElement`, and will be in future version not only `ClassElement`, but also `EnumElement`, or `MixinElement`. Right now both are also `ClassElement`, but we will separate them in the next breaking changes version. I think you might use `InterfaceElement` methods, without casting to `ClassElement`.
> 
> How should DartType be converted to InterfaceType?

```dart
TypeChecker(List).isExactly((ParameterElement.type as InterfaceElement))

error => type 'ParameterElementImpl' is not a subtype of type 'InterfaceElement' in type cast
```

**Comment by scheglov** [comment]
You don't convert, you check if it is `InterfaceType`, using `if (myType is InterfaceType) {...}`. It might be something different, e.g. `FunctionType`.

**Comment by xiaocode337317439** [comment]
> You don't convert, you check if it is `InterfaceType`, using `if (myType is InterfaceType) {...}`. It might be something different, e.g. `FunctionType`.


Thank you for answering
