### ISSUE TITLE
Is there a way from `ClassBuilder` to `ExpressionBuilder`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/code_builder#39]
I build the class declaration for class `AppComponent` (for library `a_lib`) and need the type as parameter like
```dart
ClassBuilder appComponent = ...;
final mainMethod = new MethodBuilder.returnVoid('main')
..addStatement(AngularPlatformBrowser.bootstrapFunction
        .call([appComponent]))
               ^^^^^^^^^^^^
```
    
What is a good way to get from `appComponent` to the `ExpressionBuilder` required by `call([...])`

I hope you don't mind that I ask a few questions here to master the first hurdles.

**Comment by matanlurey** [comment]
No worries.

So `ClassBuilder` doesn't consider itself a type, though I imagine that is an enhancement option.

A simple way if it's in the same file anyway might be just to reference it, i.e.

```dart
.call([reference('AppComponent')])
``

**Comment by zoechi** [comment]
Ok. So if it's in a different file I need to create a `ReferenceBuilder` with the import path of where the class will be created myself?

**Comment by matanlurey** [comment]
Yep, or the shorthand `reference('AppComponent', 'package:app/app.dart')`.

**Comment by zoechi** [comment]
Got it. Thanks a lot :)
