### ISSUE TITLE
update to allow for an unnamed library

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/code_builder#438]
When trying to add an annotation to a library w/o a name, I get:

```
Bad state: a library name is required for annotations
```

However, as of a recent (`3.0`?) version of Dart, we no longer require library names for library directives.

**Comment by srawlins** [comment]
I'm happy to make this fix

**Comment by devoncarew** [comment]
That would be great! I ran into this while working on package:web (generated code from the Web IDLs) and had to work around the issue.

**Comment by devoncarew** [comment]
fixed by https://github.com/dart-lang/code_builder/pull/440
