### ISSUE TITLE
Need travis and code-coverage integration

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/code_builder#5]
While you are at it, the CLA bot and other goodies too ;)

- [x] travis
- [ ] coverage
- [x] CLA labels

**Comment by kevmoo** [comment]
https://travis-ci.org/dart-lang/code_builder is done

**Comment by matanlurey** [comment]
Nice, adding in https://github.com/dart-lang/code_builder/pull/7

**Comment by matanlurey** [comment]
Ping for coveralls.

**Comment by kevmoo** [comment]
Added. COVERALL_TOKEN set on travis, too
