### ISSUE TITLE
allow to define parameters for `lambda()`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/code_builder#59]
I couldn't find a way to define parameters

**Comment by alorenzen** [comment]
lambda() returns a MethodBuilder, which defines addNamed() and addPositional() methods via HasParameters(https://github.com/dart-lang/code_builder/blob/master/lib/src/builders/parameter.dart#L46)

**Comment by zoechi** [comment]
@alorenzen thanks, I was sure it should be there, but auto-completion didn't work properly and didn't show it which tricked me. 
Thanks for your support.
