### ISSUE TITLE
ReferenceBuilder implements ExpressionBuilder, but TypeBuilder does not

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/code_builder#62]
I would expect TypeBuilder to be a drop-in replacement for ReferenceBuilder, since TypeBuilder is the recommended way to create generic types.

**Comment by matanlurey** [comment]
So a `TypeName` is not an `Expression` - but I can allow it to be an expression when you don't specify generic parameters. Will send you a tiny PR.
