### ISSUE TITLE
`Function` causes exception

### ISSUE THREAD

**Issue by zoechi** [dart-lang/code_builder#69]
```
'package:code_builder/dart/core.dart': error: line 111 pos 26: unexpected token 'Function'
  final ReferenceBuilder Function = _ref('Function');
                         ^
Process finished with exit code 254
```

https://github.com/dart-lang/code_builder/blob/master/lib/dart/core.dart#L111
```
  /// References [dart_core.Function].
  final ReferenceBuilder Function = _ref('Function');
```
> Dart VM version: 1.22.0-edge.8cca41772d807594955c7e9312b36ab691cfc7fe (Fri Jan 27 14:35:59 2017) on "linux_x64"

> code_builder-1.0.0-beta+1

Might be related to https://github.com/dart-lang/sdk/issues/27527#issuecomment-260997772

**Comment by matanlurey** [comment]
Sorry I can't support edge releases in this repository.

Please re-open if it it occurs on dev or stable.
