### ISSUE TITLE
Invalid argument type errors

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/code_builder#80]
Cloned from master and after running `pub get` I'm getting 15 Invalid argument type errors relating to: `ValidClassMember` `ValidMemberMember` & `ValidConstructorMember`. Example below:

```
file: '/code_builder/lib/src/builders/class.dart'
severity: 'Error'
message: 'The argument type 'ValidClassMember' can't be assigned to the parameter type 'AnnotationBuilder'.'
at: '26,27'
source: 'dart'
```

<img width="1209" alt="screen shot 2017-02-18 at 14 37 35" src="https://cloud.githubusercontent.com/assets/298850/23093990/aab0fd3a-f5e8-11e6-9306-7724deefbf75.png">

**Comment by matanlurey** [comment]
Hmm, travis is green and we check for analysis errors. Did you try restarting your analyzer?

I can take a look in the AM (PST).

**Comment by matanlurey** [comment]
@jimmyff Please re-open if you still see this.
