### ISSUE TITLE
Static mehtods

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/code_builder#82]
I might be missing something obvious but I can't find a way of marking a method as static, I can see that static is mentioned in `buildMethod` but I can't find how to utilise this from `MethodBuilder`.

Potentially `MethodModifier` could be developed to support statics?

**Comment by zoechi** [comment]
```dart
new ClassBuilder(...).addMethod(..., asStatic: true)
```
did it for me

**Comment by jimmyff** [comment]
Thanks @zoechi :-)
