### ISSUE TITLE
ExpressionBuilders should have an `asThrow` method.

### ISSUE THREAD

**Issue by thosakwe** [dart-lang/code_builder#84]
It would be very helpful if we could do something like:

```dart
new TypeBuilder('StateError').newInstance(['Blah blah blah']).asThrow();
```

This would also work, and might be better than the original suggestion I had:

```dart
new ThrowExpression(...)
```

 I have [a branch](https://github.com/thosakwe/code_builder/tree/as-throw) where this change is implemented as an `asThrow` method on `ExpressionBuilder` instances, but it wouldn't be difficult for me to just expose the `_ThrowExpression` class I created.

Thoughts on this? Can I go ahead and submit a PR, or was I too vague and need to clarify?

Thanks in advance.

**Comment by matanlurey** [comment]
Sounds good - send a PR!

**Comment by thosakwe** [comment]
Nice!
