### ISSUE TITLE
FR: Support creation of string literals that include newlines

### ISSUE THREAD

**Issue by filiph** [dart-lang/code_builder#87]
AFAIK, creating `"""string"""` literals isn't supported. When supplying `literal()` with a multi-line string, it will output a string with single `'` delimiters and the original newlines, resulting in syntax errors. Creating the literal manually isn't possible — StringLiteral isn't an exported class.

There's a workaround — never using `"""` in the generated code (for example, by escaping all newlines with `\n`).

I wonder if I'm missing something. If not and this functionality is supposed to be supported, let me know. I'd love to make a PR.

**Comment by matanlurey** [comment]
Happy to see this become a PR - I'm not sure what the best solution is, though. Either:

- Escape automatically with `'\n'` (we might want to do this anyway)
- Offer another way to make a multi-line string, i.e. something like:

```dart
multiLineString([
  'line1',
  'line2',
  'line3',
])
```

I'm not very creative, so suggestions welcome :)

**Comment by filiph** [comment]
I think having input like that is nice. But I'm trying to solve for something where input method is irrelevant because you provide the string from somewhere else. Example:

```dart
var fileContents = await file.readAsString();
// ...
var builder = _someType.newInstance([literal(fileContents)]);
```

> Escape automatically with `'\n'` (we might want to do this anyway)

I wonder if there are valid edge cases that would make this a bad idea. For example, what happens when the user provides a string that contains a line ending with `\`?

The naive solution I have in mind is having the following in [expression.dart:86](https://www.crossdart.info/p/code_builder/1.0.0-beta+3/src/builders/expression.dart.html#line-86):

```dart
if (value.contains('\n')) {
  // TODO: escape possible "'''" in string.
  return astFactory.simpleStringLiteral(stringToken("'''$value'''"), value);
} else {
  return astFactory.simpleStringLiteral(stringToken("'$value'"), value);
}
```

Before I start the PR — is that _too_ naive?

**Comment by matanlurey** [comment]
Sounds reasonable - certainly isn't more broken than it is today :)

**Comment by matanlurey** [comment]
Thanks!
