### ISSUE TITLE
published version 1.0.0-beta+4 seems to be invalid

### ISSUE THREAD

**Issue by zoechi** [dart-lang/code_builder#89]
![image](https://cloud.githubusercontent.com/assets/405837/23451594/d5e840a0-fe60-11e6-91ab-f95a020de839.png)

**Comment by matanlurey** [comment]
That's interesting considering Travis passed. I'll do a +1 release and fix today.

**Comment by zoechi** [comment]
Yup, very weird.

**Comment by matanlurey** [comment]
Fixed at `1.0.0-beta+5`.
