### ISSUE TITLE
Create a typedef

### ISSUE THREAD

**Issue by zoechi** [dart-lang/code_builder#90]
I haven't found a way to do that

**Comment by zoechi** [comment]
Seems there is also no way to create one using `xxxx.raw()`

**Comment by matanlurey** [comment]
Unfortunately it's hard to make `xxxx.raw` too generic.

I might take a shot at doing something like `RawAstBuilder`:

```dart
abstract class RawAstBuilder<T extends AstNode> {}
```

At minimum it will let us get to 1.0-final without implementing every feature in Dart.

**Comment by zoechi** [comment]
I expected `Raw('some string')` to implement every builder interface and then just emit the string,
but I haven't investigated enough yet to fully understand how the source is generated.
