### ISSUE TITLE
Support function type as parameter type

### ISSUE THREAD

**Issue by zoechi** [dart-lang/code_builder#92]
I tried to create a parameter like `updates(AccountBuilder b)` as in
```dart
 factory Account([updates(AccountBuilder b)]) = _$Account;
```

**Comment by matanlurey** [comment]
I'm not even sure how to describe this - I guess something like a `ParameterBuilder`?

```dart
factory ParameterBuilder.withFunctionType(...)
```

?

**Comment by zoechi** [comment]
sounds good to me
