### ISSUE TITLE
support shorthand function syntax for methods

### ISSUE THREAD

**Issue by zoechi** [dart-lang/code_builder#99]
I use this code to create the method below
```
..addMethod(
          method('valueOf', [
            reference(className.pascalCase),
            parameter('name', [lib$core.String]),
            reference(r'_$valueOf').call([reference('name')]).asReturn()
          ]),
          asStatic: true)
```

```dart
  static AuthRegisterLocationAccuracy valueOf(String name) {
    return _$valueOf(name);
  }
```
but I need 
```dart
  static AuthRegisterLocationAccuracy valueOf(String name) => _$valueOf(name);
```
See also google/built_value.dart#159

**Comment by matanlurey** [comment]
Looks fine to me: https://github.com/dart-lang/code_builder/issues/99

**Comment by zoechi** [comment]
Did you mean to link to something else? Currently the link in your comment just points to this issue ;-)

**Comment by matanlurey** [comment]
Err, https://github.com/dart-lang/code_builder/pull/103

**Comment by zoechi** [comment]
Thanks, using `new MethodBuilder()` instead of `method()` worked for me.
